-- barbecue.nvim is currently disabled.
-- To re-enable, uncomment below and call `require("plugins.barbecue")` from
-- lua/plugins/init.lua.
--
-- vim.pack.add({
-- 	"https://github.com/SmiteshP/nvim-navic",
-- 	"https://github.com/nvim-tree/nvim-web-devicons",
-- 	"https://github.com/utilyre/barbecue.nvim",
-- })
--
-- require("barbecue").setup({
-- 	kinds = {
-- 		Array = "",
-- 		Boolean = "",
-- 		Class = "",
-- 		Color = "",
-- 		Constant = "",
-- 		Constructor = "",
-- 		Enum = "",
-- 		EnumMember = "",
-- 		Event = "",
-- 		Field = "",
-- 		File = "󰈙",
-- 		Folder = "",
-- 		Function = "",
-- 		Interface = "",
-- 		Key = "",
-- 		Keyword = "",
-- 		Method = "",
-- 		Module = "",
-- 		Namespace = "",
-- 		Null = "",
-- 		Number = "",
-- 		Object = "",
-- 		Operator = "",
-- 		Package = "",
-- 		Property = "",
-- 		Reference = "",
-- 		Snippet = "",
-- 		String = "",
-- 		Struct = "",
-- 		Text = "",
-- 		TypeParameter = "",
-- 		Unit = "",
-- 		Value = "",
-- 		Variable = "",
-- 	},
-- })
